// Models/ComplianceMetadata.swift
// C2PA-style provenance metadata attached to every AI-generated repair guide.
import Foundation
import SwiftUI

// MARK: – C2PA Metadata

struct ComplianceMetadata: Sendable {
    /// Human-readable AI model name shown in disclosure.
    let producerName: String
    /// ISO-8601 timestamp when the content was generated.
    let generatedAt: Date
    /// Software version claim (bundle short version).
    let appVersion: String
    /// AI model identifier used for this content.
    let modelIdentifier: String

    static func current(modelID: String = Config.geminiModel) -> ComplianceMetadata {
        ComplianceMetadata(
            producerName:    Config.c2paProducerName,
            generatedAt:     Date(),
            appVersion:      Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0",
            modelIdentifier: modelID
        )
    }

    /// A formatted provenance string for display or export.
    var provenanceString: String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return "Generated by \(producerName) using \(modelIdentifier) at \(formatter.string(from: generatedAt))"
    }
}

// MARK: – AI Disclosure Badge (SwiftUI)

/// Compact disclosure chip shown under any AI-generated content.
/// Required by App Store guidelines and Amazon PA-API affiliate rules.
struct AIDisclosureBadge: View {
    var text: String = Config.aiDisclosureText
    var systemImage: String = "wand.and.sparkles"

    var body: some View {
        Label(text, systemImage: systemImage)
            .font(.system(size: 11, weight: .medium))
            .foregroundStyle(.secondary)
            .padding(.horizontal, 10)
            .padding(.vertical, 5)
            .background(.ultraThinMaterial, in: Capsule())
            .overlay(Capsule().strokeBorder(Color.white.opacity(0.1), lineWidth: 0.5))
    }
}

// MARK: – Affiliate Disclaimer (SwiftUI)

/// One-liner Amazon affiliate disclosure — required under Associates program rules.
struct AffiliateDisclaimerBadge: View {
    var body: some View {
        Text(Config.affiliateDisclaimer)
            .font(.system(size: 10))
            .foregroundStyle(.tertiary)
            .multilineTextAlignment(.center)
            .padding(.horizontal, Theme.spacingM)
    }
}
